INSERT INTO `districts` (`id`, `name`) VALUES
(1, 'Balaraja'),
(2, 'Cikupa'),
(3, 'Cisauk'),
(4, 'Cisoka'),
(5, 'Curug'),
(6, 'Gunung Kaler'),
(7, 'Jambe'),
(8, 'Jayanti'),
(9, 'Kelapa Dua'),
(10, 'Kemiri'),
(11, 'Kosambi'),
(12, 'Kresek'),
(13, 'Kronjo'),
(14, 'Legok'),
(15, 'Mauk'),
(16, 'Mekarbaru'),
(17, 'Pagedangan'),
(18, 'Pakuhaji'),
(19, 'Panongan'),
(20, 'Pasar Kemis'),
(21, 'Rajeg'),
(22, 'Sepatan'),
(23, 'Sepatan Timur'),
(24, 'Sindang Jaya'),
(25, 'Solear'),
(26, 'Sukadiri'),
(27, 'Sukamulya'),
(28, 'Teluknaga'),
(29, 'Tigaraksa');
